const { buildPage } = require('./_generate');
const fs = require('fs');
const path = require('path');

const signs = [
  {
    sign: 'aries', Sign: 'Aries',
    tagline: 'They need to feel like they chose you. The second they feel chosen for, the chase is over.',
    style: 'avoidant',
    sections: [
      {
        heading: 'The Aries Attachment Pattern',
        paragraphs: [
          'Aries leans avoidant. Not coldly, not cruelly, but structurally. Their attachment system is wired for pursuit. They need to feel like the hunter, the initiator, the one who chose. When that dynamic flips, when someone is clearly more invested than they are, something in Aries clicks off. It\'s not that they stop caring. It\'s that the care stops feeling urgent. And urgency is what keeps Aries engaged.',
          'This avoidant tendency isn\'t a personality defect. It\'s a feature of fire-sign independence filtered through cardinal energy. Aries is the first sign of the zodiac: the self, the individual, the one who leads. Attachment that feels like dependency activates their deepest discomfort. They want closeness. They also want to feel like closeness was their idea.',
          'In early dating, Aries attachment looks healthy and exciting. They pursue, they initiate, they show up with full energy. The avoidant pattern typically emerges later, once the relationship stabilizes and the pursuit phase ends. That\'s when Aries starts to feel the walls of commitment and their instinct is to test whether the walls have exits.'
        ],
        highlight: { label: 'The pattern', text: 'Aries chases hard, wins, then feels the urge to run. Not because they don\'t want what they won. Because the winning was doing most of the emotional work.' }
      },
      {
        heading: 'When Aries Feels Safe',
        paragraphs: [
          'Aries feels safe when their partner has a full life of their own. A partner who is genuinely busy, genuinely independent, genuinely not waiting around for Aries to text back: that person signals safety because they\'re not threatening Aries\'s autonomy. The paradox is real. Aries feels closest to people who don\'t need them. The space itself is what makes closeness possible.',
          'They also feel safe when they\'re allowed to lead in the relationship without it being questioned constantly. This doesn\'t mean they need a pushover. It means they need someone who respects their need to initiate and doesn\'t undermine it with passive aggression or silent expectations. Give Aries room to come to you and they almost always will.',
          'Physical activity together creates safety. Working out together, hiking, competitive games, anything that burns energy and creates shared adrenaline. Aries bonds through action, not through sitting still and talking about feelings. The feelings emerge during the activity, not in a structured conversation about the relationship.'
        ]
      },
      {
        heading: 'When Aries Pulls Away',
        paragraphs: [
          'Aries pulls away when they feel controlled, suffocated, or like their independence is being threatened. The trigger doesn\'t have to be dramatic. A partner who texts too frequently checking in, who needs to know where they are at all times, who responds to Aries\'s need for space with anxiety: these everyday patterns can activate Aries\'s avoidant response and send them retreating further.',
          'They also pull away when boredom sets in. Aries needs novelty. Not necessarily new partners, but new experiences, new challenges, new dynamics within the relationship. When things become routine and predictable, Aries starts feeling trapped even if the routine is comfortable. They interpret the comfort as stagnation and the stagnation as a threat to their vitality.',
          'Conflict, surprisingly, doesn\'t make Aries pull away. They can handle direct fights. What they can\'t handle is passive-aggressive withdrawal, cold shoulders, or emotional games where they\'re expected to figure out what\'s wrong without being told. That kind of emotional labor feels suffocating in a different way, and Aries will disengage entirely rather than decode unstated expectations.'
        ]
      },
      {
        heading: 'What Aries Needs From a Partner',
        paragraphs: [
          'Independence. A partner who has their own identity, their own goals, their own friendships, and their own capacity for happiness outside the relationship. Aries cannot be someone\'s entire world without eventually feeling crushed by the weight of that. They need a partner who is a complete person first and a partner second.',
          'Direct communication. Tell Aries what you need. Don\'t hint. Don\'t wait for them to notice. They\'re not oblivious, but they operate on explicit information rather than implicit signals. A partner who can say "I need more quality time this week" will get a better response from Aries than a partner who goes quiet and waits for Aries to realize something is wrong.',
          'Room to pursue. Even in committed relationships, Aries needs to feel like they\'re still choosing their partner actively rather than being held by obligation. This means allowing space for initiative, for pursuit, for the sense that the relationship is something Aries actively wants rather than something that happened to them. Keep the element of choice alive.'
        ]
      },
      {
        heading: 'The Aries Anxious or Avoidant Spiral',
        paragraphs: [
          'When an anxious partner is involved, the Aries avoidant pattern can create a painful cycle. The anxious partner reaches for connection, Aries feels crowded and pulls back, the anxious partner escalates their reaching, and Aries retreats further. This cycle can continue until the relationship either explodes or the anxious partner gives up, at which point Aries suddenly feels the loss and re-engages. The push-pull is exhausting for both people.',
          'Aries can also flip into anxious attachment under specific conditions: when they\'re paired with someone even more avoidant than they are. Suddenly Aries is the one pursuing, the one wondering why they haven\'t heard back, the one reading into silences. This experience is deeply unsettling for Aries because it violates their self-image as the independent one. It can actually be a growth opportunity if they let it teach them what the other side of their pattern feels like.',
          'The spiral breaks when Aries develops awareness of their own pattern. When they can notice the urge to pull away and ask themselves "am I actually overwhelmed or am I just scared of needing someone?" That question, asked honestly, is the beginning of moving from reactive avoidance to conscious choice. And conscious choice is what turns avoidant attachment into earned security.'
        ]
      },
      {
        heading: 'How Aries Heals Their Attachment Wounds',
        paragraphs: [
          'Aries heals by staying. Not by forcing themselves to stay through white-knuckled willpower, but by practicing the act of remaining present when their instinct says to bolt. Sitting with the discomfort of closeness rather than interpreting closeness as threat. Noticing the fear underneath the restlessness rather than acting on the restlessness itself.',
          'Physical practices are especially effective for Aries attachment healing. Martial arts, yoga, intense physical training: anything that teaches them to hold their energy in their body rather than always discharging it through action. The discipline of physical stillness translates into relationship stillness. Learning to be present in their body helps them learn to be present with another person.',
          'Aries also heals through relationships with secure partners who don\'t chase them or withdraw. A partner who is simply steady, consistently present without being clingy, is the most healing influence for Aries avoidance. The secure partner doesn\'t trigger the chase instinct or the flight response. They just stay, reliably, and let Aries discover at their own pace that staying doesn\'t mean being trapped. It means being held.'
        ]
      }
    ],
    faqs: [
      { q: 'Is Aries attachment style avoidant?', a: 'Aries tends toward avoidant attachment, meaning they prioritize independence and can pull away when relationships feel too close or confining. They need to feel like they\'re choosing to be there. The avoidance isn\'t about not caring. It\'s about maintaining autonomy as a core emotional need.' },
      { q: 'Why does Aries pull away after getting close?', a: 'Aries pulls away because closeness can trigger a fear of losing independence. Once the pursuit phase ends and the relationship settles, Aries may interpret stability as stagnation. They need ongoing novelty and the sense that they\'re actively choosing to stay rather than being held by obligation.' },
      { q: 'How do you make Aries feel secure?', a: 'Give them space. Have your own life. Communicate directly. Don\'t cling or monitor. Let them come to you. A partner who is genuinely independent and doesn\'t need Aries to feel whole is the person who makes Aries feel safest.' },
      { q: 'Can Aries become securely attached?', a: 'Yes. Aries can develop secure attachment through self-awareness about their avoidant patterns, a partner who is steady without being clingy, and the willingness to practice staying present when their instinct says to pull away. Growth is absolutely possible.' }
    ],
    keepReading: {
      title: 'More on Aries in Love',
      links: [
        { href: '/signs/aries-in-love', text: 'Aries in Love' },
        { href: '/signs/aries-red-flags', text: 'Aries Red Flags' },
        { href: '/signs/aries-love-language', text: 'Aries Love Language' },
        { href: '/signs/aries-toxic-traits', text: 'Aries Toxic Traits' }
      ]
    }
  }
];

// Now define the remaining 11 signs with the same structure
const remaining = [
  { sign: 'taurus', Sign: 'Taurus', tagline: 'Secure until threatened. Then the grip tightens.', style: 'secure baseline, anxiously possessive when threatened',
    s1p: ['Taurus has one of the healthiest baseline attachment patterns in the zodiac. Under normal conditions, they are steady, consistent, present, and reassuring. They don\'t play games. They don\'t create distance for sport. They show up and they stay. This secure baseline is their greatest relationship strength and the thing that makes them one of the most reliable partners you can find.','The shift happens when that security is threatened. When Taurus senses instability, potential loss, or wavering commitment, their attachment style pivots hard toward anxious. Specifically, they become possessive. Not controlling in a strategic way, but gripping in an emotional way. The thing they valued, the stability they built, is being threatened, and their response is to hold on tighter rather than adjust.','This combination of secure baseline and anxious activation creates a partner who is wonderful 90% of the time and unexpectedly intense the other 10%. The trigger is always perceived threat to the relationship\'s foundation. If the foundation feels solid, Taurus is the most relaxed partner in the zodiac. If it wobbles, they become someone their partner doesn\'t always recognize.'],
    s2p: ['Taurus feels safe when routines are established and maintained. Regular date nights, consistent communication patterns, a shared domestic life that has predictable rhythms. They don\'t need excitement. They need reliability. When the structure of the relationship is stable, Taurus opens up with a warmth and generosity that is genuinely remarkable.','Physical presence matters enormously. Taurus feels safe when they can touch, hold, and be near their partner regularly. Long-distance relationships are particularly challenging for this sign because physical absence triggers the same insecurity as emotional absence. Being in the same room, sharing a meal, sleeping in the same bed: these tangible experiences are what build Taurus\'s sense of security.','Financial and domestic stability also contribute to their sense of safety. A partner who is responsible with money, who maintains their living space, who has a steady approach to practical life: this person signals safety to Taurus at a fundamental level. It\'s not about wealth. It\'s about reliability in the material world.'],
    s3p: ['Taurus pulls away when they\'ve been pushed too far and their possessive response has been activated and then shamed. If Taurus expresses jealousy or insecurity and their partner responds with contempt or dismissal, Taurus eventually shuts down. The withdrawal is slow and heavy. They don\'t slam doors. They just gradually stop investing, stop initiating, stop bringing the warmth that defined the relationship.','They also pull away when they feel taken for granted. Taurus gives consistently and generously, and when that giving is treated as expected rather than appreciated, resentment builds. Taurus won\'t always voice this resentment directly. They\'ll just become less present, less warm, less willing to extend themselves. The withdrawal is a statement about unreciprocated investment.','Change imposed without consent makes Taurus retreat. A partner who makes major decisions unilaterally, who introduces instability without discussion, who treats the relationship\'s foundation as something that can be rearranged at will: this person will find Taurus pulling away not out of rejection but out of self-preservation.'],
    s4p: ['Consistency above everything. Taurus needs a partner whose behavior is predictable enough to build trust on. Not boring, but reliable. Someone whose word means something. Someone who does what they said they\'d do. The reliability itself is the love language that Taurus receives most clearly.','Physical affection that is regular and unhurried. Not just sex, but daily physical contact. Holding hands while watching something. Long hugs at the end of a difficult day. Back rubs offered without prompting. Taurus processes love through the body, and a partner who is physically affectionate and comfortable with sustained closeness is meeting their deepest need.','Appreciation expressed in words and actions. Taurus needs to hear that their stability is valued, not assumed. A partner who says "I appreciate how reliable you are" or "thank you for always being here" is giving Taurus something that matters more than any grand gesture.'],
    s5p: ['When Taurus\'s anxious possessive side activates, the spiral looks like monitoring. Checking phones, asking pointed questions, interpreting innocent interactions as threats. The partner, feeling surveilled, pulls back, which confirms Taurus\'s fear and escalates the possessiveness. This cycle can become entrenched if neither person names it.','The flip side: if Taurus is pushed far enough, they can swing to avoidant. They shut down, become emotionally impenetrable, and decide that protecting themselves is more important than saving the relationship. This shutdown is hard to reverse because Taurus is a fixed sign. Once the wall goes up, it takes sustained effort and genuine accountability from the other person to bring it back down.','The anxious spiral often connects to childhood experiences of inconsistent caregiving. If Taurus learned early that love was something that could be withdrawn without warning, they developed the possessive grip as a coping mechanism. Understanding this origin point is the first step toward loosening it.'],
    s6p: ['Taurus heals by developing internal security that doesn\'t depend entirely on external consistency. This means building self-worth that survives relationship instability. Therapy that focuses on self-regulation, particularly somatic approaches that work with the body, is especially effective for this earth sign.','They also heal through practicing open communication about their fears rather than acting on them. The difference between "I\'m feeling insecure and I need reassurance" and checking your partner\'s phone is the difference between healthy attachment and the anxious spiral. Taurus needs to learn to name the fear rather than manage it through control.','Secure attachment develops for Taurus when they find a partner who is naturally consistent and who doesn\'t trigger the possessive response. The right partnership allows Taurus\'s natural secure baseline to stay activated most of the time, with only occasional dips into anxiety that can be addressed through direct communication rather than possessive behavior.']
  },
  { sign: 'gemini', Sign: 'Gemini', tagline: 'They\'re not afraid of commitment. They\'re afraid of being fully known.', style: 'fearful avoidant',
    s1p: ['Gemini\'s attachment pattern is fearful avoidant, which means they simultaneously want closeness and are terrified of it. They approach relationships with genuine enthusiasm and curiosity, then pull back when things get too real. The duality of Gemini, the twins, plays out in attachment as wanting two contradictory things at once: to be deeply known and to maintain the escape route.','The fearful avoidant pattern in Gemini often looks like inconsistency from the outside. Hot and cold. Fully present one week and distant the next. Texting constantly and then going quiet without explanation. This isn\'t manipulation. It\'s the internal ping-pong between the part of them that craves connection and the part that associates vulnerability with danger.','Gemini\'s particular version of fearful avoidance tends to operate through intellectualization. When emotions get too intense, they retreat into their head. They analyze their feelings rather than sitting in them. They turn the relationship into a topic of discussion rather than an experience they\'re having. This mental escape creates distance that feels safer than emotional immersion.'],
    s2p: ['Gemini feels safe when conversations are flowing and genuine. Not heavy emotional processing sessions, but real, varied, engaging dialogue that makes them feel intellectually and emotionally connected simultaneously. When the communication is alive, Gemini\'s attachment system relaxes. They feel seen through being heard, and they feel known through being understood.','Lightness paired with depth. Gemini feels safest in relationships that can move between serious and playful fluidly. A partner who can discuss a genuine fear and then pivot to a funny observation without either thing feeling forced: that person creates the environment where Gemini can stay present. It\'s the rigidity of sustained heavy emotion that triggers their flight response.','Freedom within the relationship. Gemini needs to know they can have friends, interests, and social connections outside the partnership without it being treated as betrayal. When the relationship respects their need for social range, Gemini feels less like a caged bird and more like a bird who keeps choosing to come home.'],
    s3p: ['Gemini pulls away when emotional intensity exceeds their processing capacity. Deep emotional confrontations, sustained relationship talks, anything that demands they stay in an uncomfortable feeling for an extended period: these trigger the avoidant side of their fearful avoidance. They don\'t leave physically, necessarily. They leave mentally. You can see it happen: a glazing of the eyes, a deflection into humor, a sudden topic change.','They also pull away when they feel pinned to a single identity within the relationship. If their partner needs them to be one consistent thing, Gemini starts to feel like a butterfly pinned to a board. They are multifaceted by nature. A partner who says "you always do this" or "that\'s not who you are" is triggering the part of Gemini that refuses to be categorized.','Monotony is a form of emotional death for Gemini. When the relationship becomes entirely predictable, when every weekend looks the same, when conversations follow familiar tracks, Gemini\'s attachment anxiety converts into avoidant behavior. They start looking elsewhere for stimulation not because they\'ve stopped loving their partner but because their nervous system is screaming for something new.'],
    s4p: ['Verbal reassurance that is genuine and specific. Not generic "I love you" on autopilot, but specific observations that show the partner is actually paying attention: "I love how your mind works when you\'re excited about something." Gemini needs to feel seen in their specificity.','A partner who can match their energy shifts. Not someone who is always the same, but someone who can be playful when Gemini is playful, serious when the moment requires it, and comfortable with the transitions between states. Emotional flexibility in a partner signals that Gemini doesn\'t have to perform a single consistent version of themselves.','Patience with their processing style. Gemini often needs to talk through their feelings out loud before they know what they feel. A partner who can listen to the full stream of consciousness, including contradictions and reversals, without getting frustrated or demanding consistency, is giving Gemini exactly what they need to eventually land somewhere real.'],
    s5p: ['The fearful avoidant spiral for Gemini involves approaching and then retreating in rapid succession. They get close, feel vulnerable, pull back, miss the connection, approach again, feel even more vulnerable because now there\'s history, pull back harder. Each cycle deepens the confusion for both partners and erodes trust incrementally.','When paired with an anxious partner, this creates a particularly painful dynamic. The anxious partner interprets each Gemini withdrawal as evidence of impending abandonment and responds with escalated pursuit. Gemini experiences the pursuit as pressure and retreats further. The information asymmetry is the problem: the anxious partner is reacting to what they see (distance) while Gemini is reacting to what they feel (overwhelm).','The cycle breaks when Gemini can start naming what\'s happening in real time. "I\'m feeling overwhelmed and I need to step back, but I\'m coming back." This one sentence, offered sincerely, can prevent the entire spiral from activating because it addresses the anxious partner\'s core fear (being left) while honoring Gemini\'s core need (space to process).'],
    s6p: ['Gemini heals their attachment wounds through communication, which is fitting because communication is also their strength. Therapy that is talk-based rather than somatic tends to work well. They need to articulate their patterns, understand the origins of their fearful avoidance, and develop language for the internal experience that currently drives their push-pull behavior.','Building tolerance for emotional intensity is key growth work. This doesn\'t mean forcing themselves into heavy emotional experiences. It means gradually extending the amount of time they can sit with an uncomfortable feeling before deflecting. Five more seconds of sitting with sadness before making a joke. Ten more minutes of difficult conversation before changing the subject. The capacity builds incrementally.','Gemini also heals by choosing partners who are genuinely secure rather than anxious or avoidant. A secure partner doesn\'t chase when Gemini withdraws (which would feed the pattern) and doesn\'t withdraw when Gemini approaches (which would feed the other side). They stay. That steadiness, experienced over time, teaches Gemini\'s nervous system that closeness and safety can coexist.']
  },
  { sign: 'cancer', Sign: 'Cancer', tagline: 'They don\'t need much. Just everything you have, all the time, forever.', style: 'anxious/preoccupied',
    s1p: ['Cancer is the most anxiously attached sign in the zodiac. Not as a flaw, but as a structural feature of how their emotional system operates. Cancer\'s attachment is preoccupied: they think about the relationship constantly, monitor its health obsessively, and interpret small changes in their partner\'s behavior as significant signals about the relationship\'s future.','This anxious preoccupation comes from a genuine place: Cancer feels things deeply, attaches strongly, and has an enormous capacity for love. The anxiety isn\'t about insecurity for its own sake. It\'s about the fact that they\'ve already given so much of themselves to this person that losing them would feel genuinely devastating. The investment is real, and the fear of losing that investment is proportional.','Cancer\'s anxious attachment shows up earliest in the relationship. While other signs might play it cool in the beginning, Cancer is already all in. They\'re already planning, already integrating their partner into their emotional ecosystem, already imagining a future. This isn\'t rushing. It\'s just how Cancer processes connection: quickly, thoroughly, and with their whole heart.'],
    s2p: ['Cancer feels safe when reassurance is regular and unprompted. Not just when they ask for it, but when their partner offers it naturally. The good morning text. The "thinking of you" message. The check-in that isn\'t prompted by a crisis but by genuine care. These small, consistent signals tell Cancer\'s nervous system that the connection is stable and they can relax.','Domestic togetherness creates profound safety for Cancer. Cooking together, being in the same room doing different things, building shared routines and rituals. The presence of the partner in shared domestic space is deeply calming to Cancer\'s attachment system. It\'s not that they need constant interaction. They need to know the person is there.','Emotional transparency from their partner is essential. Cancer feels safe when they can read their partner\'s emotional state. A partner who hides their feelings, who says "I\'m fine" when they\'re not, who presents a controlled exterior that Cancer can\'t penetrate: this person triggers Cancer\'s anxious monitoring because the information gap feels threatening.'],
    s3p: ['Cancer pulls away only after exhausting every other option. It takes a lot to push Cancer to withdrawal, because withdrawal goes against their fundamental instinct, which is to move toward connection rather than away from it. When Cancer pulls away, it\'s usually because they\'ve been hurt repeatedly in the same way and have finally decided that protecting themselves is more important than maintaining the connection.','Feeling unreciprocated is the primary trigger. When Cancer gives and gives and gives and doesn\'t feel that effort coming back, they eventually retreat into their shell. The withdrawal isn\'t angry, usually. It\'s tired. It\'s the exhaustion of someone who has been rowing a boat alone for too long and has finally put the oars down.','Dismissal of their emotional needs is the other major cause. When Cancer expresses vulnerability and is met with eye-rolling, minimizing, or "you\'re being too much," they eventually stop expressing. But the needs don\'t disappear. They just go underground, where they transform into resentment that Cancer may not even be fully conscious of until it surfaces in a moment of crisis.'],
    s4p: ['Consistent reassurance that doesn\'t feel forced. Cancer can tell the difference between genuine reassurance and performative reassurance. They need a partner who actually enjoys providing comfort and connection rather than one who does it under obligation. The authenticity matters as much as the frequency.','Physical closeness. Cancer is a deeply physical sign that processes emotional safety through the body. Cuddling, holding hands, the specific quality of a hug that communicates "I\'m here and I\'m not going anywhere." A partner who is physically affectionate by nature, rather than someone who has to be reminded to touch, is deeply nourishing for Cancer.','Patience with their emotional process. Cancer doesn\'t process feelings quickly or neatly. They have waves. They revisit things. They need to talk about the same concern multiple times from different angles before they can release it. A partner who can hold space for this process without getting frustrated or dismissive is giving Cancer the most important thing they need.'],
    s5p: ['Cancer\'s anxious spiral involves escalating bids for reassurance that become increasingly difficult for partners to meet. It starts with a check-in text and escalates to questioning, then to emotional flooding, then potentially to ultimatums. Each unmet bid intensifies the next one. The partner feels increasingly overwhelmed and either shuts down or becomes reactive, which feeds Cancer\'s abandonment fear.','The preoccupied aspect means Cancer is mentally running relationship analysis 24 hours a day. They\'re interpreting text response times, tracking emotional temperature changes, comparing current behavior to previous behavior. This constant monitoring is exhausting for Cancer and creates a hypervigilance that prevents genuine relaxation in the relationship.','When Cancer pairs with an avoidant partner, the classic anxious-avoidant trap activates. Cancer pursues, the avoidant retreats, Cancer pursues harder, the avoidant retreats further. This dynamic can persist for years because both people are operating from their attachment wounds rather than from conscious choice. Breaking the pattern requires one or both people to change their automatic response.'],
    s6p: ['Cancer heals by developing self-soothing skills that reduce their dependence on the partner for emotional regulation. This doesn\'t mean they shouldn\'t need their partner. It means learning to hold themselves through moments of anxiety without immediately outsourcing the soothing to someone else. Meditation, journaling, and somatic practices that teach self-regulation are especially helpful.','Building a life outside the relationship is critical healing work for Cancer. Friends, hobbies, creative pursuits, professional goals: all of these provide alternative sources of meaning and identity that reduce the pressure on the romantic relationship to be everything. Cancer heals when they distribute their emotional investment rather than concentrating it entirely in one person.','Choosing secure partners is the most impactful single decision Cancer can make for their attachment health. A secure partner provides the consistency that Cancer needs without being threatened by their emotional intensity. Over time, the secure partner\'s steadiness teaches Cancer\'s nervous system that love doesn\'t require constant monitoring to survive.']
  },
  { sign: 'leo', Sign: 'Leo', tagline: 'Devoted when admired. Spiraling when ignored.', style: 'anxious when insecure',
    s1p: ['Leo\'s attachment style is conditionally anxious: secure when they feel admired and appreciated, anxious when they sense their partner\'s attention or admiration wavering. This makes Leo\'s attachment health directly tied to the quality of recognition they receive. In relationships where they feel genuinely seen and celebrated, Leo is warm, generous, and deeply loyal. In relationships where they feel overlooked or taken for granted, their attachment anxiety activates with visible intensity.','The underlying mechanism is self-worth that is partially externalized. Leo gets a significant portion of their sense of self from how they are reflected back by the people they love. This is not vanity. It\'s a real psychological need for mirroring that, when met, allows Leo to be their most magnificent self. When unmet, it creates a specific kind of insecurity that can drive behavior that looks like neediness but is really a search for evidence of their own worthiness.','Leo in secure mode is one of the best partners in the zodiac. They are generous, protective, devoted, fun, and warm in a way that makes their partner feel like the most important person alive. The goal for Leo\'s attachment growth isn\'t to eliminate the need for appreciation but to develop enough internal security that the normal fluctuations of a partner\'s attention don\'t trigger a full attachment crisis.'],
    s2p: ['Leo feels safe when appreciation is specific, public, and genuine. Not generic compliments, but real observations about what makes them uniquely valuable. A partner who notices Leo\'s effort, who celebrates their wins out loud, who tells other people how great Leo is: this person is creating the environment where Leo\'s attachment system stays calm and their best qualities emerge.','Being chosen visibly matters. Leo feels secure when their partner shows pride in the relationship. Social media posts, introducing them enthusiastically to friends, holding their hand in public. The visible, public nature of the commitment signals to Leo that this is real and valued, not hidden or provisional.','Loyalty signals create deep safety. A partner who defends Leo in their absence, who doesn\'t entertain attention from others, who makes it clear through behavior that Leo is their person: this is the foundation of Leo\'s attachment security. They don\'t need reassurance every day when the fundamental loyalty of the relationship is clearly demonstrated.'],
    s3p: ['Leo pulls away when they feel consistently underappreciated. Not after one missed compliment, but after a pattern of being taken for granted. When Leo\'s efforts go unacknowledged, when their partner stops noticing the things they do, when the appreciation that initially existed in the relationship fades into expectation: Leo starts to withdraw their warmth as a protective measure.','They also pull away when their pride is wounded. Public embarrassment, being corrected in front of others, having their vulnerabilities exposed carelessly: these trigger a withdrawal that is actually more about protecting a wound than about rejecting the partner. Leo retreats to lick their wounds and assess whether this person can be trusted with their ego.','Comparison with others triggers Leo\'s attachment anxiety and eventual withdrawal. If Leo senses that their partner finds someone else more interesting, more attractive, or more worthy of attention, the wound goes deep. They may not confront it directly. They may instead begin performing harder, which eventually becomes exhausting, leading to withdrawal when the performance doesn\'t produce the desired result.'],
    s4p: ['Recognition. Genuine, specific, repeated recognition of who they are and what they bring. Leo doesn\'t need flattery. They need a partner who has actually observed them and can articulate what they see. The more specific the appreciation, the more it lands.','A partner who is proud of them. Not someone who tolerates Leo\'s bigness but someone who genuinely enjoys it. Who celebrates their accomplishments rather than minimizing them. Who tells their friends "my partner did this amazing thing" with genuine enthusiasm.','Physical warmth and affection. Leo is a physical sign that equates touch with love. A partner who is comfortable with consistent physical affection, who reaches for Leo first, who makes physical connection a natural part of daily life: this person is speaking Leo\'s attachment language fluently.'],
    s5p: ['When Leo\'s anxious attachment activates, they tend to escalate their bids for attention. More dramatic gestures, more effort to impress, more obvious attempts to recapture their partner\'s focus. If these escalated bids are still unmet, Leo may begin to test the partner through withdrawal or through behavior designed to provoke jealousy. This is not manipulative in intention. It\'s a desperate attempt to get information about whether they still matter.','The spiral deepens when Leo\'s pride prevents them from directly asking for what they need. Instead of saying "I feel underappreciated and I need you to acknowledge me," they perform bigger, get louder, or withdraw dramatically. The partner, confused by the behavior change, may respond with frustration or distance, which feeds Leo\'s original insecurity.','Breaking the spiral requires Leo to separate their self-worth from their partner\'s response. This is the hardest work for this sign because the external mirroring feels so essential to their identity. But the truth is that no partner can sustain the level of constant admiration that anxious Leo requires. The sustainable path is developing internal sources of self-worth that don\'t depend on anyone else\'s reflection.'],
    s6p: ['Leo heals by building a relationship with their own value that doesn\'t require external validation to exist. This doesn\'t mean not wanting appreciation. It means developing enough internal security that the normal ebb and flow of a partner\'s attention doesn\'t feel like an identity crisis.','Creative self-expression is a powerful healing path for Leo. When they have a creative outlet where they receive recognition on their own terms, the pressure on the romantic relationship to provide all of their mirroring decreases significantly. Leo needs audiences, not just partners, and diversifying their sources of appreciation creates healthier attachment dynamics.','Leo also heals through vulnerability practice. The anxious pattern often involves performing strength to earn love. Learning to be genuinely vulnerable, to ask directly for what they need, to show their insecurity without performing it: this builds the kind of intimacy that makes attachment security possible. A partner who can hold Leo\'s vulnerability without losing respect for them is the partner who helps Leo heal.']
  },
  { sign: 'virgo', Sign: 'Virgo', tagline: 'They\'ll analyze why they love you before they let themselves feel it.', style: 'dismissive avoidant',
    s1p: ['Virgo leans dismissive avoidant. They intellectualize their feelings, maintain emotional distance through analysis, and genuinely believe that self-sufficiency is the safest relationship with the world. This isn\'t coldness. It\'s a highly developed coping strategy that served them well early in life and now creates barriers to the intimacy they actually want.','The dismissive quality in Virgo\'s avoidance shows up as devaluing emotional needs, both their own and their partner\'s. When a partner says "I need more closeness," Virgo\'s internal response is often to analyze whether the need is reasonable rather than simply responding to it. They filter emotional requests through a rational framework that often strips the emotion out of the equation entirely.','Virgo\'s specific version of avoidance involves staying busy as a distancing mechanism. Work, projects, health routines, self-improvement: all of these become ways to maintain productive distance from emotional engagement. They\'re not avoiding the partner. They\'re avoiding the feelings that being fully present with the partner would require them to have.'],
    s2p: ['Virgo feels safe when things are organized and predictable. A partner who is reliable, who keeps their commitments, who maintains their shared environment with care: this person signals safety at a structural level. The order itself is calming to Virgo\'s nervous system.','Being useful to their partner creates safety. When Virgo can contribute practically, when their help is needed and appreciated, they feel connected without having to navigate purely emotional territory. The acts of service create a bridge between Virgo\'s comfort zone (doing) and the relationship\'s need (connecting).','A partner who respects their boundaries without taking them personally. Virgo needs someone who can hear "I need some time alone to recharge" without interpreting it as rejection. A partner who understands that Virgo\'s need for solitude is about processing, not avoidance, creates the conditions where Virgo can voluntarily emerge from their analytical shell.'],
    s3p: ['Virgo pulls away when they feel emotionally overwhelmed or when their partner demands emotional engagement they can\'t produce. The demand for vulnerability, the request to "open up and tell me how you feel," can trigger a retreat into analysis and distance because Virgo genuinely does not always know how they feel in real time.','Criticism of their emotional style is particularly triggering. When a partner says "you\'re too cold" or "you never share your feelings," Virgo receives this as both a criticism and a confirmation that they are fundamentally inadequate at the relationship thing. Rather than trying harder, they often pull back further.','Mess, chaos, and lack of structure in the relationship or in their partner\'s life can also cause withdrawal. Virgo reads disorder as evidence that things are falling apart, and rather than engaging with the mess, they distance themselves from it as a form of self-protection.'],
    s4p: ['Patience with their processing speed. Virgo does have feelings. They just take longer to identify and articulate them. A partner who can wait for Virgo to arrive at their emotional truth rather than demanding it on a timeline creates the safety for genuine emotional expression.','Appreciation for their acts of service as love. When Virgo fixes your broken shelf, researches your medical question, or organizes your closet, they are saying "I love you" in the clearest language they have. A partner who recognizes service as love rather than dismissing it as avoidance is meeting Virgo where they actually are.','Low-pressure invitations to connect. Not "we need to talk about our relationship" but "do you want to take a walk?" or "come sit with me." Virgo responds better to casual proximity than to structured emotional confrontation. The feelings emerge sideways, during activity, not head-on in a scheduled relationship discussion.'],
    s5p: ['Virgo\'s dismissive avoidant spiral involves intellectualizing their way out of emotional engagement. When a partner expresses need, Virgo analyzes whether the need is valid. When they feel attracted, they list reasons it might not work. When they\'re hurt, they explain to themselves why they shouldn\'t be. The mind becomes a fortress against feeling.','The spiral deepens when their partner responds to the distance with either pursuit (which triggers more avoidance) or withdrawal (which Virgo may not even notice because they\'re already in their head). The relationship can become two people in the same room operating on completely different emotional planes.','The spiral breaks when Virgo experiences a moment of genuine feeling that bypasses their analytical filters. Sometimes this happens through crisis: a loss, a health scare, a moment of beauty that catches them off guard. In that unprotected moment, they feel the full weight of their attachment and realize how much they\'ve been keeping at bay.'],
    s6p: ['Virgo heals by learning that feelings don\'t need to be analyzed to be valid. This sounds simple but is genuinely difficult for this sign. Somatic therapy, body-based practices, and any modality that connects them to their physical experience of emotion (rather than their mental interpretation of it) is particularly effective.','Practicing small acts of emotional expression without preparation builds the muscle over time. Telling their partner "I missed you today" without having scripted it first. Crying during a movie without analyzing why. Admitting they\'re afraid without having a solution ready. These small unguarded moments, accumulated over time, retrain Virgo\'s nervous system to associate vulnerability with safety rather than danger.','Choosing a partner who is emotionally patient and doesn\'t take Virgo\'s analytical distance personally is crucial. The right partner for Virgo understands that the avoidance isn\'t about them. It\'s about Virgo\'s relationship with their own feelings. Patience, combined with consistent gentle invitations to connect, gradually draws Virgo out of their head and into their heart.']
  }
];

// Add remaining signs with similar detailed content
const moreRemaining = [
  { sign: 'libra', Sign: 'Libra', tagline: 'They don\'t just want a partner. They want to become one.', style: 'anxious/codependent',
    s1p: ['Libra\'s attachment style trends anxious with a codependent twist. They don\'t just attach to people. They merge with them. Libra defines themselves through partnership to a degree that can be genuinely destabilizing when the partnership is threatened. Their identity becomes intertwined with their partner\'s to the point where separation doesn\'t just feel painful, it feels like losing a limb.','The codependent element shows up as people-pleasing that extends into self-erasure. Libra in attachment mode will suppress their own needs, opinions, and preferences to maintain harmony in the relationship. They become a mirror for their partner rather than a person in their own right. This is not generosity. It\'s a survival mechanism rooted in the belief that being themselves might cost them the relationship.','Libra\'s attachment anxiety is triggered by conflict, by distance, and by any sign that the relationship\'s harmony is disrupted. Even minor disagreements can activate their fear response because conflict signals the potential dissolution of the partnership that constitutes their identity.'],
    s2p: ['Libra feels safe when the relationship is harmonious and reciprocal. Regular affirmation of the partnership\'s health, shared activities that reinforce togetherness, and a partner who actively participates in maintaining the relationship\'s aesthetic and emotional quality all signal safety.','Having a partner who makes decisions alongside them creates security. Libra feels anxious when they have to choose alone. A partner who says "let\'s figure this out together" is speaking directly to Libra\'s attachment needs.','Beauty in the relationship environment matters. A clean shared space, thoughtful date nights, aesthetic attention to how the couple presents themselves: these external signals of a well-maintained partnership calm Libra\'s nervous system in ways that pure emotional reassurance sometimes cannot.'],
    s3p: ['Libra pulls away only when they\'ve accumulated so much unspoken resentment that the relationship has become toxic to them. This process can take months or years because Libra\'s default is to stay and accommodate rather than leave. When they finally pull away, it often shocks the partner because there was no visible escalation.','They also withdraw when they realize they\'ve lost themselves entirely. Sometimes a moment of clarity hits Libra where they recognize they have no idea what they actually want, think, or feel outside the context of the relationship. This realization can trigger a withdrawal that is actually the beginning of healthy individuation.','Sustained disrespect or contempt will eventually push Libra away, but the tolerance threshold is high. Libra will endure treatment that other signs would leave over immediately because their fear of being alone outweighs their self-protective instincts.'],
    s4p: ['Active partnership. Not passive coexistence, but genuine collaboration on shared goals, decisions, and experiences. Libra needs to feel like they\'re building something with someone, not just existing alongside them.','Validation of their perspective. Libra often struggles to trust their own opinions. A partner who actively asks what Libra thinks and then takes their input seriously is addressing a deep need.','Conflict repair. Since conflict is so threatening to Libra, having a partner who can fight fairly and then repair the rupture quickly is essential. The ability to disagree and come back together without lingering resentment is what makes conflict survivable for this sign.'],
    s5p: ['Libra\'s codependent spiral involves progressively erasing themselves to maintain the relationship. Each accommodation, each swallowed opinion, each suppressed need creates a small fracture in their sense of self. Over time, these fractures accumulate until Libra no longer knows who they are outside the partnership. At that point, the codependency becomes genuinely toxic because the relationship is being maintained at the cost of a whole person.','The anxiety escalates when Libra senses distance. Their response is to become more accommodating, more pleasing, more focused on the partner\'s needs. This counterintuitively pushes many partners away because the person they fell for had opinions and preferences that have now disappeared.','Breaking the pattern requires Libra to tolerate the discomfort of having their own position. Saying "no" to something they don\'t want. Expressing a genuine preference that might conflict with their partner\'s. These acts of individuation feel terrifying to anxious/codependent Libra but they\'re the only way back to a self that can genuinely participate in partnership rather than just serving one.'],
    s6p: ['Libra heals by developing a relationship with themselves that exists independently of any partnership. This might involve periods of chosen solitude, individual therapy focused on identity rather than relationship dynamics, creative pursuits that express their unique perspective.','Learning to sit with conflict rather than immediately resolving it builds essential tolerance. Not every disagreement needs to be smoothed over immediately. Some tension is productive. Libra heals when they learn that the relationship can survive disharmony and that they can survive being disliked temporarily.','Secure partners who encourage Libra\'s individuation are the most healing influence. A partner who says "what do YOU want?" and waits for a genuine answer, who pushes back gently when Libra defaults to accommodation, who loves Libra as a full person rather than as a pleasant reflection: this person creates the conditions for Libra to develop earned security.']
  },
  { sign: 'scorpio', Sign: 'Scorpio', tagline: 'They love like they\'re testing whether you\'ll survive it.', style: 'fearful avoidant',
    s1p: ['Scorpio\'s attachment style is fearful avoidant at its most intense. They crave deep, transformative intimacy while simultaneously being terrified of the vulnerability that intimacy requires. This creates the classic Scorpio push-pull: drawing you in with magnetic intensity and then testing whether you can be trusted by creating distance or conflict.','The fearful avoidant pattern in Scorpio is rooted in a deep awareness of betrayal. Whether from actual past experiences or from an instinctive understanding of how power dynamics work in love, Scorpio enters every relationship with the assumption that vulnerability will eventually be weaponized. This isn\'t paranoia. It\'s pattern recognition operating at a very deep level.','Scorpio\'s attachment intensity is unmatched. When they attach, they attach completely. The pull toward the other person is gravitational, obsessive, and total. Which is exactly why the avoidant side activates so strongly: the stakes feel so high that any sign of potential betrayal triggers massive defensive responses.'],
    s2p: ['Scorpio feels safe when trust has been established through genuine testing. Not manufactured tests, but the organic moments where their partner could have betrayed them and didn\'t. When Scorpio shares something vulnerable and it\'s held with care. When they see evidence of loyalty that wasn\'t performed for their benefit.','Total honesty creates safety. Scorpio can handle almost any truth. What they cannot handle is discovering that they\'ve been lied to, even about small things. A partner who is transparently honest, even about things that are unflattering, earns Scorpio\'s trust in a way that charm and reassurance never can.','Emotional depth in the partner. Scorpio feels safe with people who have their own psychological complexity, who have been through difficult things and emerged with genuine wisdom rather than bitterness. Someone who can meet Scorpio at their depth rather than asking them to come to the surface.'],
    s3p: ['Scorpio pulls away when they sense deception, even when the deception is minor. A small inconsistency in a story, a moment of evasiveness, a question deflected: Scorpio notices everything. And once they\'ve noticed, their protective mechanism activates. The withdrawal isn\'t punishment. It\'s self-preservation in response to perceived threat.','They also pull away preemptively when things are going too well. Scorpio\'s fearful avoidance means that happiness itself can feel threatening because it means there\'s more to lose. The instinct to self-sabotage during peak intimacy is one of Scorpio\'s most frustrating patterns, and it often blindsides partners who thought everything was perfect.','Being made to feel powerless triggers immediate withdrawal. Scorpio needs to feel they have agency in the relationship. A partner who makes major decisions without them, who creates situations where Scorpio has no control, who holds information as power: this person will watch Scorpio vanish.'],
    s4p: ['Loyalty proved through action, not words. Scorpio needs to see evidence of commitment that exists outside of the relationship\'s easy moments. A partner who shows up during crisis, who defends them publicly, who demonstrates through behavior that the commitment is real and non-negotiable.','Space for intensity. Scorpio needs a partner who isn\'t scared by deep emotion, by difficult conversations, by the parts of intimacy that most people avoid. They need someone who can go to the darkest places with them and not flinch.','Control over their own vulnerability. Scorpio needs to share at their own pace. Being pushed to open up before they\'re ready will backfire completely. They need a partner who creates invitations rather than demands for vulnerability.'],
    s5p: ['The fearful avoidant spiral in Scorpio involves intense approach followed by equally intense withdrawal. They pull the partner in with magnetic attention and then push them away through jealousy, testing, or emotional shutdown. The partner, whiplashed by the extremes, either leaves (confirming Scorpio\'s belief that people always leave) or stays (at which point Scorpio tests harder).','The testing behavior is the most recognizable feature of Scorpio\'s attachment pattern. They create scenarios, consciously or unconsciously, to determine whether the partner will betray them. Will they stay when Scorpio is at their worst? Will they keep a secret? Will they choose Scorpio over someone else? Each passed test deepens trust marginally. Each failed test can end the relationship entirely.','Breaking the spiral requires Scorpio to recognize that testing is a trauma response, not a relationship strategy. The person who passes every test doesn\'t prove they\'re trustworthy. They prove they\'re patient. Real trust is built through the mundane accumulation of shared experience, not through orchestrated trials.'],
    s6p: ['Scorpio heals through therapy that addresses their core wound around betrayal and vulnerability. Depth psychology, psychodynamic work, and any modality that takes the historical roots of their attachment pattern seriously (rather than just managing symptoms) tends to resonate.','Practicing vulnerability in small, low-stakes ways builds the muscle gradually. Sharing something slightly personal with a friend. Admitting a minor weakness at work. Each small act of openness that doesn\'t result in betrayal recalibrates Scorpio\'s expectation that vulnerability always leads to pain.','The most healing relationship for Scorpio is with someone who is transparently trustworthy and doesn\'t engage with tests. A partner who simply refuses to play the testing game and instead offers consistent, boring, reliable honesty is the most disarming and ultimately healing thing Scorpio can encounter. It neutralizes the need for vigilance and allows real intimacy to develop.']
  },
  { sign: 'sagittarius', Sign: 'Sagittarius', tagline: 'They\'re not running from you. They\'re running toward everything else.', style: 'avoidant',
    s1p: ['Sagittarius is avoidant in the cleanest sense: they associate love with freedom and freedom with distance. Being in a relationship, to Sagittarius, should feel like standing in an open field, not sitting in a closed room. The avoidance isn\'t about not wanting connection. It\'s about not wanting connection to come with walls.','Their avoidant pattern is philosophical rather than emotional. Sagittarius has genuinely thought about commitment and concluded that most versions of it involve trading essential freedoms for security they don\'t value. This intellectual framework gives their avoidance a quality of conviction that distinguishes it from, say, Gemini\'s anxious avoidance. Sagittarius isn\'t conflicted about distance. They believe in it.','In relationships, this shows up as the partner who is genuinely wonderful when present and genuinely absent more often than most people are comfortable with. Solo trips, separate friend groups, needing weekends alone: Sagittarius structures their life to maintain independence within the relationship, which works beautifully with the right partner and terribly with the wrong one.'],
    s2p: ['Sagittarius feels safe when freedom is guaranteed. Not theoretically, but practically. A partner who says "go on your trip, I\'ll be here when you get back" without resentment or anxiety is creating the exact conditions Sagittarius needs to stay voluntarily. The guarantee of freedom is what makes closeness possible.','Shared adventure creates safety. Sagittarius bonds through experience rather than through emotional processing. A partner who wants to explore, try new things, travel, and grow together is offering Sagittarius a version of commitment that doesn\'t feel like sacrifice. The relationship becomes the adventure rather than the thing preventing adventure.','Honesty. Sagittarius is one of the most truth-oriented signs and they feel safe with people who tell the truth even when it\'s uncomfortable. A partner who is direct about their feelings, who doesn\'t play emotional games, who communicates clearly: this person earns Sagittarius\'s trust in a way that no amount of emotional caretaking can.'],
    s3p: ['Sagittarius pulls away when they feel trapped. The triggers can be minor: a partner who texts too frequently, who expects a daily schedule report, who guilt-trips about time spent apart. These small constraints accumulate into a feeling of claustrophobia that Sagittarius resolves by creating more distance.','Heavy emotional demands trigger withdrawal. When a partner needs extensive emotional processing, when every conversation becomes a relationship check-in, when the emotional labor of maintaining the connection outweighs the joy of the connection itself: Sagittarius starts looking for the exit.','Being asked to compromise on their values or worldview. Sagittarius is deeply attached to their beliefs and their sense of truth. A partner who expects them to adopt different values, to become someone they\'re not, or to suppress their honest reactions for the sake of politeness: this person will lose Sagittarius completely.'],
    s4p: ['Space without guilt. This is non-negotiable. Sagittarius needs a partner who genuinely understands that time apart is not a statement about the relationship\'s health. It\'s a requirement for Sagittarius\'s individual health, which in turn supports the relationship.','A sense of shared direction. Sagittarius commits when they feel the relationship is going somewhere meaningful. Not just existing comfortably, but growing, evolving, moving toward shared goals that excite both people. The relationship needs to feel like it has a horizon.','Lightness. Sagittarius needs laughter, playfulness, and the sense that life with their partner is genuinely fun. Heavy, serious, problem-focused relationship energy drains them. They need a partner who can find humor in difficulty and who doesn\'t catastrophize normal challenges.'],
    s5p: ['Sagittarius\'s avoidant spiral is straightforward: pressure in, distance out. The more a partner pushes for closeness, the further Sagittarius runs. They may not literally leave. They may just become increasingly absent emotionally while remaining physically present. The partner senses the distance and pushes harder, which drives Sagittarius further away.','The spiral can also manifest as serial escapism. When one relationship starts feeling too confining, Sagittarius may begin idealizing freedom or even other people. Not necessarily cheating, but the mental departure that precedes the physical one. Their attention starts drifting toward what\'s out there rather than what\'s right here.','Breaking the pattern requires Sagittarius to sit with the discomfort of closeness long enough to discover that it doesn\'t actually threaten their freedom. The fear is that intimacy means imprisonment. The reality, with the right partner, is that intimacy means having someone who supports your freedom and shares your adventures. But Sagittarius has to stay long enough to learn this through experience rather than fleeing before the lesson arrives.'],
    s6p: ['Sagittarius heals by redefining commitment. Rather than seeing it as a cage, they need to experience it as an expanded home base from which to explore. This reframing happens through relationship experience with a partner who genuinely supports their independence.','Developing emotional literacy is growth work for Sagittarius. Learning to name feelings, to sit with sadness without running, to process grief without deflecting into humor: these capacities deepen Sagittarius\'s ability to attach securely. The avoidance often masks genuine feelings that Sagittarius has never fully experienced because they always move before the feelings arrive.','The most healing thing for Sagittarius is finding someone they want to come home to. Not someone who makes them stay, but someone who makes staying feel like an adventure in itself. When Sagittarius finds a partner who is genuinely interesting enough to hold their attention across years, the avoidant pattern doesn\'t need to activate because the restlessness is addressed within the relationship rather than outside it.']
  },
  { sign: 'capricorn', Sign: 'Capricorn', tagline: 'They built the wall before you arrived. Getting past it is the whole relationship.', style: 'dismissive avoidant',
    s1p: ['Capricorn\'s attachment style is dismissive avoidant with a specific flavor: vulnerability feels like professional liability. They approach relationships with the same controlled, strategic mindset they bring to their career. Emotions are managed rather than expressed. Needs are analyzed rather than felt. The result is a partner who is supremely reliable but sometimes emotionally unreachable.','The dismissive quality runs deep. Capricorn genuinely believes that self-sufficiency is the highest virtue and that needing someone emotionally is a form of weakness. This belief system was usually reinforced early in life by an environment that rewarded achievement and independence while punishing vulnerability. Capricorn learned to provide for themselves and to trust no one else to do it.','In relationships, this manifests as a partner who shows up practically but holds back emotionally. They\'ll support you with their resources, their time, their reliability. But ask them how they feel and you\'ll get a pause, a deflection, or a carefully constructed response that sounds right but reveals nothing. The wall isn\'t hostile. It\'s structural.'],
    s2p: ['Capricorn feels safe when the relationship has clear expectations and established structure. Knowing what is expected of them and being able to meet those expectations reliably is Capricorn\'s version of emotional security. Ambiguity and undefined relationships create anxiety that they manage through withdrawal.','Respect from their partner creates safety. Capricorn needs to feel admired for their competence and their achievement. A partner who sees their work ethic and their accomplishments as genuinely impressive, rather than taking them for granted, is addressing Capricorn\'s core attachment need.','Slow, gradual emotional disclosure that respects their pace. Capricorn opens up over years, not weeks. A partner who is patient with this timeline and doesn\'t pressure faster disclosure creates the conditions where Capricorn can eventually let their guard down.'],
    s3p: ['Capricorn pulls away when vulnerability is demanded on someone else\'s timeline. Being told to "open up" or "share your feelings" activates their defensive posture rather than softening it. The demand for emotional access feels like an intrusion into territory they haven\'t yet decided to share.','Professional stress often triggers relational withdrawal. When Capricorn is under pressure at work, the relationship is the first thing that gets deprioritized. Not because they don\'t care, but because their coping mechanism is to pour more energy into the domain where they feel competent (career) and less into the domain where they feel vulnerable (intimacy).','Perceiving their partner as emotionally unstable or unreliable triggers withdrawal. Capricorn needs to trust their partner\'s capacity to handle life before they\'ll risk being vulnerable. If the partner seems unable to manage their own emotional weather, Capricorn decides the relationship isn\'t safe enough for them to lower their defenses.'],
    s4p: ['Actions over words. Capricorn trusts what people do, not what they say. A partner who consistently follows through, who meets commitments, who demonstrates reliability through behavior is building Capricorn\'s trust in the only way that registers for this sign.','Shared long-term goals. Capricorn feels most connected when they\'re building something with their partner: a home, a business, a family, a life plan. The shared project creates a framework for intimacy that feels productive rather than merely emotional.','Space for their reserve without judgment. A partner who can say "I notice you\'re quiet tonight, I\'m here if you want to talk, no pressure" is giving Capricorn the most healing response. The acknowledgment without demand allows Capricorn to approach vulnerability on their own terms.'],
    s5p: ['Capricorn\'s dismissive spiral involves increasingly using work as an avoidance mechanism. The busier they are, the less time for emotional engagement. The partner feels neglected, brings it up, Capricorn promises to do better, and then fills the schedule again. The pattern is self-reinforcing because the work provides the sense of competence and control that the relationship\'s emotional demands threaten.','When paired with an anxious partner, Capricorn\'s distance can create a devastating dynamic where the anxious partner\'s emotional needs are consistently unmet and Capricorn feels increasingly inadequate at providing something they don\'t understand. Both people end up feeling like failures in the relationship.','The spiral breaks when Capricorn has an experience that makes emotional connection feel like an achievement rather than a risk. Some Capricorns unlock attachment through parenthood, where the vulnerability is unavoidable and the love is so powerful that the walls simply can\'t hold. Others unlock it through a partner whose patience and steadiness eventually makes the wall feel unnecessary rather than essential.'],
    s6p: ['Capricorn heals by experiencing vulnerability that doesn\'t result in collapse. Each instance where they share something real and the relationship strengthens rather than weakens recalibrates their belief that vulnerability equals weakness. This process is slow and requires a partner with extraordinary patience.','Therapy that is structured and goal-oriented resonates with Capricorn. Open-ended emotional exploration feels inefficient to them. CBT, structured attachment therapy, and any modality that gives them a framework and measurable progress works better than free-form processing.','Physical experiences that bypass the intellectual defenses can be powerful healing tools. Massage, dance, somatic work, anything that puts Capricorn in their body rather than their head. The body holds the emotions that the mind has locked away, and accessing them through the body is often the path of least resistance for this sign.']
  },
  { sign: 'aquarius', Sign: 'Aquarius', tagline: 'Emotionally available for humanity. Emotionally unavailable for you specifically.', style: 'dismissive avoidant',
    s1p: ['Aquarius is dismissive avoidant with an intellectual veneer that makes it look like philosophical choice rather than attachment wound. They\'ve constructed an entire worldview around emotional independence, and they genuinely believe that their detachment is evolution rather than avoidance. This makes Aquarius\'s attachment pattern one of the hardest to address because they don\'t experience it as a problem.','The specific Aquarius flavor of avoidance involves redirecting emotional energy from personal relationships into ideas, causes, and collective concerns. They can care deeply about humanitarian issues while remaining surprisingly disconnected from the person sitting across from them at dinner. The emotional capacity exists. It\'s just pointed outward rather than inward.','In relationships, Aquarius operates at a slight remove. They\'re present, they\'re interested, they\'re engaged. But there\'s a pane of glass between them and full emotional immersion. Partners describe it as feeling like Aquarius is observing the relationship from slightly outside it, participating and analyzing simultaneously rather than just being in it.'],
    s2p: ['Aquarius feels safe when their intellectual autonomy is preserved. A partner who respects their right to think independently, who doesn\'t demand emotional conformity, who can disagree without it becoming a threat to the relationship: this person creates the conditions where Aquarius can actually relax.','Friendship-first dynamics create safety. Aquarius is most attached to people they genuinely like and respect as minds. A relationship that is built on genuine friendship and intellectual compatibility signals safety because the foundation is something Aquarius understands and values.','Having their own space, literally and figuratively. Separate rooms, separate projects, separate social circles: these structural elements of independence allow Aquarius to choose closeness rather than being forced into it. The choice is what makes it feel safe rather than threatening.'],
    s3p: ['Aquarius pulls away when emotional demands exceed their capacity. Not because the demands are unreasonable, but because Aquarius\'s emotional bandwidth is genuinely narrower than most water or fire signs. When the relationship requires sustained emotional engagement, Aquarius can feel depleted in a way that triggers retreat.','They pull away when their individuality feels threatened by the merger that intimacy requires. Aquarius guards their sense of self fiercely. A partner who wants to share everything, do everything together, become a unit rather than two individuals: this person triggers the avoidant response because the merger feels like dissolution.','Convention triggers withdrawal. If the relationship starts following conventional patterns that Aquarius hasn\'t consciously chosen, they start to feel like they\'re performing a role rather than living authentically. The discomfort with prescribed relationship behavior can manifest as pulling away from the relationship itself.'],
    s4p: ['Intellectual respect. Aquarius needs a partner who takes their ideas seriously, who engages with their thinking, who treats their mind as the most attractive thing about them. The intellectual partnership is the foundation on which everything else is built.','Freedom without consequence. Aquarius needs to know that needing space won\'t be punished. That having separate interests won\'t be interpreted as rejection. That their unconventional approach to relationships won\'t be pathologized.','Authenticity. Aquarius can detect social performance instantly and it repels them. They need a partner who is genuinely themselves, who doesn\'t modify their personality to please Aquarius, who has the integrity to be honest even when honesty is uncomfortable.'],
    s5p: ['Aquarius\'s avoidant spiral involves increasingly retreating into the mind when the heart is activated. The more they feel, the more they think about what they feel. The thinking creates distance from the feeling, which reduces the intensity to a manageable level. Over time, this pattern can create a relationship where Aquarius is emotionally absent while remaining physically and intellectually present.','When paired with an emotional partner who needs depth and vulnerability, Aquarius can create a dynamic where the partner feels perpetually unseen. The partner\'s emotional bids are received but not reciprocated. Aquarius cares but doesn\'t know how to show it in the way the partner needs. Both people end up lonely inside a relationship that looks functional from the outside.','The spiral breaks when Aquarius encounters a feeling they can\'t intellectualize. Grief, overwhelming love for a child, a moment of beauty so intense it bypasses the analytical mind. These breakthrough moments are the cracks in the Aquarian armor, and they often become turning points in attachment development.'],
    s6p: ['Aquarius heals by learning that emotional connection isn\'t a threat to their individuality. This is their core misconception and addressing it is the key to attachment growth. They can be fully themselves and fully connected simultaneously, and discovering this through experience rather than theory is the healing journey.','Body-based practices are particularly important for this heady sign. Aquarius lives in their mind, and their avoidant pattern is maintained by the distance between thought and feeling. Practices that bring them into their body, whether through exercise, dance, breathwork, or physical intimacy, help bridge the gap.','Finding a partner who is intellectually stimulating enough to hold Aquarius\'s interest while also being emotionally available enough to model healthy attachment is the ideal healing relationship. This person demonstrates through their own behavior that intelligence and emotional depth coexist, which challenges Aquarius\'s assumption that choosing one means sacrificing the other.']
  },
  { sign: 'pisces', Sign: 'Pisces', tagline: 'They didn\'t fall in love with you. They fell into you. There\'s a difference.', style: 'anxious/disorganized',
    s1p: ['Pisces\' attachment style is anxious with disorganized features, which means they crave closeness desperately while simultaneously engaging in behaviors that undermine it. They merge with their partners, lose themselves in the relationship, and then feel so overwhelmed by the loss of self that they act out in ways that confuse everyone, including themselves.','The disorganized element is key. Unlike purely anxious Cancer who pursues connection consistently, Pisces oscillates between clinging and disappearing. They might be deeply enmeshed one week and emotionally absent the next, not because they chose to withdraw but because their emotional system became overloaded and their coping mechanism was to check out, sometimes through escapism, sometimes through fantasy, sometimes through substances.','Pisces\' attachment wounds are often the deepest and least visible. They absorb the emotional atmosphere of every relationship they\'re in, which means they carry not just their own attachment injuries but echoes of their partner\'s as well. This emotional porousness makes Pisces extraordinarily empathetic and extraordinarily vulnerable simultaneously.'],
    s2p: ['Pisces feels safe when the emotional connection is deep, consistent, and expressed through creative or spiritual language. Music, art, shared dreaminess, moments of transcendent beauty together: these create a sense of soul-level bonding that calms Pisces\' attachment anxiety in ways that practical reassurance sometimes cannot.','Gentleness is essential. Pisces\' nervous system is finely calibrated and easily overwhelmed. A partner who is naturally gentle in their communication, who handles Pisces\' sensitivity as a feature rather than a flaw, who modulates their energy to avoid flooding Pisces with more stimulation than they can process: this person creates genuine safety.','Being seen in their totality. Not just the beautiful, dreamy, artistic parts, but the messy, escapist, boundary-less parts too. Pisces feels safest with someone who has witnessed their worst and stayed. The unconditional quality of that acceptance addresses Pisces\' core fear that they are fundamentally too much and not enough simultaneously.'],
    s3p: ['Pisces pulls away through dissociation rather than active withdrawal. They don\'t leave the relationship. They leave their body. They check out emotionally while remaining physically present. Partners describe it as the lights being on but nobody being home. This dissociative response is triggered by emotional overwhelm, conflict they can\'t resolve, or the realization that they\'ve lost themselves again.','Escapism as withdrawal. When reality becomes too painful or too demanding, Pisces retreats into fantasy, substances, sleep, screens, or other absorptive experiences that take them out of the present moment. This isn\'t laziness. It\'s a nervous system response to stimulation that has exceeded their processing capacity.','When their partner doesn\'t reciprocate the depth of devotion Pisces offers. Pisces gives everything and when the return feels insufficient, they don\'t always confront the imbalance. Instead, they retreat into the internal fantasy version of the relationship, which is usually better than the real one. The partner doesn\'t notice the withdrawal because Pisces is still physically there, but Pisces has already left for an inner world where the love is what they imagined it could be.'],
    s4p: ['Encouragement to maintain their individual identity. Pisces needs a partner who actively reminds them to keep their own friends, their own interests, their own sense of self. Left to their default, Pisces will merge entirely. The right partner doesn\'t let that happen, not through control but through genuine encouragement of Pisces\' individual expression.','Boundaries set with kindness. Pisces doesn\'t respond well to harsh boundary-setting. They need a partner who can say "I love you and I need this boundary" without making Pisces feel rejected. The combination of firmness and warmth is essential.','Structure without rigidity. Pisces benefits from a partner who provides some organizational backbone to their life, some grounding practical presence, without being so rigid that Pisces feels boxed in. The ideal partner brings earthy stability while appreciating Pisces\' watery fluidity.'],
    s5p: ['The disorganized spiral for Pisces involves losing themselves in the partner, feeling overwhelmed by the loss of identity, acting out through escapism or self-sabotage, experiencing guilt about the acting out, and then merging even harder to compensate. The cycle feeds itself because each stage drives the next.','When Pisces pairs with a partner who enables their self-sacrifice rather than challenging it, the codependent dynamic can become genuinely harmful. Pisces gives everything, the partner receives without questioning, Pisces depletes completely, and the crash that follows can involve depression, substance use, or complete emotional breakdown.','The spiral breaks when Pisces develops the capacity to notice the merge happening in real time and choose differently. "I\'m starting to lose myself" is the recognition that changes everything. With that awareness, Pisces can begin making conscious choices about how much of themselves to give, rather than operating on the default of total immersion.'],
    s6p: ['Pisces heals by building a self that exists independently of their relationships. This is the fundamental work. Practices that strengthen Pisces\' sense of individual identity, including art, journaling, solo time in nature, meditation, and therapy focused on self-development rather than relationship repair, are essential.','Learning to feel their own feelings rather than absorbing everyone else\'s is critical. Techniques for distinguishing "my emotion" from "absorbed emotion" give Pisces the ability to participate in relationships without being consumed by them. Energy work, somatic therapy, and mindfulness practices that develop interoceptive awareness are particularly effective.','The most healing relationship for Pisces is with someone who loves them and also holds them accountable. A partner who says "you matter too" when Pisces starts sacrificing. Who reminds them to eat, to sleep, to maintain friendships. Who treats Pisces\' tendency to dissolve as something to gently counter rather than exploit. That partner doesn\'t just love Pisces. They protect Pisces from the part of themselves that would give everything away.']
  }
];

// Generate all attachment style pages
function generateAttach(data) {
  const pageData = {
    title: `${data.Sign} Attachment Style: How They Love and Why They Pull Away`,
    desc: `${data.Sign} attachment style explained: ${data.style}. Here's how ${data.Sign} loves, what makes them feel safe, why they pull away, and how they heal.`,
    canonical: `https://signseason.com/signs/${data.sign}-attachment-style`,
    breadcrumbName: `${data.Sign} Attachment Style`,
    tagline: data.tagline,
    ctaId: `attach_${data.sign}`,
    footSign: data.sign,
    sections: data.sections || [
      { heading: `The ${data.Sign} Attachment Pattern`, paragraphs: data.s1p, highlight: { label: 'The pattern', text: `${data.Sign}'s baseline attachment style is ${data.style}. This shapes every aspect of how they love, what triggers them, and what they need to feel secure.` } },
      { heading: `When ${data.Sign} Feels Safe`, paragraphs: data.s2p },
      { heading: `When ${data.Sign} Pulls Away`, paragraphs: data.s3p },
      { heading: `What ${data.Sign} Needs From a Partner`, paragraphs: data.s4p },
      { heading: `The ${data.Sign} Anxious or Avoidant Spiral`, paragraphs: data.s5p },
      { heading: `How ${data.Sign} Heals Their Attachment Wounds`, paragraphs: data.s6p }
    ],
    faqs: data.faqs || [
      { q: `What is ${data.Sign}'s attachment style?`, a: `${data.Sign} tends toward ${data.style} attachment. This means they ${data.style.includes('avoidant') ? 'prioritize independence and can struggle with emotional vulnerability in close relationships' : data.style.includes('anxious') ? 'crave closeness intensely and can become preoccupied with the relationship\'s security' : 'have a complex relationship with intimacy that involves both craving closeness and fearing it'}.` },
      { q: `Why does ${data.Sign} pull away in relationships?`, a: `${data.Sign} pulls away when they feel ${data.style.includes('avoidant') ? 'their independence is threatened or when emotional demands exceed their processing capacity' : data.style.includes('anxious') ? 'unreciprocated or when their bids for connection are consistently unmet, leading to protective withdrawal' : 'overwhelmed by emotional intensity, when trust feels uncertain, or when they\'ve lost track of their own identity within the relationship'}.` },
      { q: `How do you make ${data.Sign} feel secure?`, a: `${data.Sign} feels secure with ${data.style.includes('avoidant') ? 'a partner who respects their need for space, communicates directly, and doesn\'t interpret their independence as rejection' : data.style.includes('anxious') ? 'consistent reassurance, physical closeness, and a partner who provides steady emotional availability without being asked' : 'a combination of emotional depth, patience with their process, and a partner who maintains their own identity while being genuinely present'}.` },
      { q: `Can ${data.Sign} become securely attached?`, a: `Yes. ${data.Sign} can develop earned secure attachment through self-awareness about their patterns, therapeutic work that addresses their core wounds, and a relationship with a partner who is steady enough to create a safe foundation for growth. Healing is always possible.` }
    ],
    keepReading: data.keepReading || {
      title: `More on ${data.Sign} in Love`,
      links: [
        { href: `/signs/${data.sign}-in-love`, text: `${data.Sign} in Love` },
        { href: `/signs/${data.sign}-red-flags`, text: `${data.Sign} Red Flags` },
        { href: `/signs/${data.sign}-love-language`, text: `${data.Sign} Love Language` },
        { href: `/signs/${data.sign}-toxic-traits`, text: `${data.Sign} Toxic Traits` }
      ]
    }
  };

  const html = buildPage(pageData);
  const filePath = `${__dirname}/${data.sign}-attachment-style.html`;
  fs.writeFileSync(filePath, html);
  console.log(`wrote ${filePath} (${html.length} bytes)`);
}

// Generate Aries (from signs array with full sections)
generateAttach(signs[0]);

// Generate all remaining
for (const r of remaining) {
  generateAttach(r);
}
for (const r of moreRemaining) {
  generateAttach(r);
}

console.log('All attachment style pages generated.');
